.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH hako-fetch 1  "fetch " 
.SH NAME
hako\-fetch \- HTTP client
.SH SYNOPSIS
\fBhako fetch\fR [\fB\-X\fR|\fB\-\-request\fR] [\fB\-d\fR|\fB\-\-data\fR] [\fIURL\fR] 
.SH DESCRIPTION
HTTP client
.SH OPTIONS
.TP
\fB\-X\fR, \fB\-\-request\fR \fI<method>\fR
HTTP method
.TP
\fB\-d\fR, \fB\-\-data\fR \fI<body>\fR
request body
.TP
[\fIURL\fR]

