.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH hako-dig 1  "dig " 
.SH NAME
hako\-dig \- DNS lookup
.SH SYNOPSIS
\fBhako dig\fR [\fB\-t\fR|\fB\-\-type\fR] [\fIdomain\fR] 
.SH DESCRIPTION
DNS lookup
.SH OPTIONS
.TP
\fB\-t\fR, \fB\-\-type\fR \fI<type>\fR
record type (A, AAAA, MX, TXT, NS, CNAME)
.TP
[\fIdomain\fR]

