.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH hako-traceroute 1  "traceroute " 
.SH NAME
hako\-traceroute \- trace route to host
.SH SYNOPSIS
\fBhako traceroute\fR [\fB\-m \fR] [\fB\-q \fR] [\fIhost\fR] 
.SH DESCRIPTION
trace route to host
.SH OPTIONS
.TP
\fB\-m\fR \fI<hops>\fR
max hops
.TP
\fB\-q\fR \fI<probes>\fR
probes per hop
.TP
[\fIhost\fR]

