.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH hako-httpserver 1  "httpserver " 
.SH NAME
hako\-httpserver \- serve a directory over HTTP
.SH SYNOPSIS
\fBhako httpserver\fR [\fB\-\-tls\fR] [\fIdirectory\fR] [\fIport\fR] 
.SH DESCRIPTION
serve a directory over HTTP
.SH OPTIONS
.TP
\fB\-\-tls\fR
enable TLS
.TP
[\fIdirectory\fR]

.TP
[\fIport\fR]

