.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH hako-uname 1  "uname " 
.SH NAME
hako\-uname \- print system info
.SH SYNOPSIS
\fBhako uname\fR [\fB\-a \fR] [\fB\-s \fR] [\fB\-n \fR] [\fB\-r \fR] [\fB\-v \fR] [\fB\-m \fR] 
.SH DESCRIPTION
print system info
.SH OPTIONS
.TP
\fB\-a\fR
all info
.TP
\fB\-s\fR
kernel name
.TP
\fB\-n\fR
node name
.TP
\fB\-r\fR
kernel release
.TP
\fB\-v\fR
kernel version
.TP
\fB\-m\fR
machine hardware
