.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH hako 1  "hako " 
.SH NAME
hako \- tiny toybox
.SH SYNOPSIS
\fBhako\fR [\fIsubcommands\fR]
.SH DESCRIPTION
tiny toybox
.SH SUBCOMMANDS
.TP
hako\-hello(1)
print hello
.TP
hako\-time(1)
print current time
.TP
hako\-rand(1)
print random number
.TP
hako\-sleep(1)
sleep for duration
.TP
hako\-overwrite(1)
overwrite file contents
.TP
hako\-asn(1)
look up ASN for IP
.TP
hako\-calc(1)
evaluate math expressions
.TP
hako\-dig(1)
DNS lookup
.TP
hako\-dnsname(1)
reverse DNS lookup
.TP
hako\-httpserver(1)
serve a directory over HTTP
.TP
hako\-tar(1)
create or extract tar archives
.TP
hako\-env(1)
print environment variables
.TP
hako\-which(1)
locate a command
.TP
hako\-whois(1)
WHOIS lookup
.TP
hako\-hostname(1)
print hostname
.TP
hako\-uname(1)
print system info
.TP
hako\-fetch(1)
HTTP client
.TP
hako\-ping(1)
ping a host
.TP
hako\-traceroute(1)
trace route to host
.TP
hako\-tlscheck(1)
inspect TLS certificate
.TP
hako\-ciphers(1)
list supported TLS ciphers
.TP
hako\-md5sum(1)
compute MD5 checksum
.TP
hako\-sha256sum(1)
compute SHA\-256 checksum
.TP
hako\-completions(1)
print shell completions
.TP
hako\-redirect(1)
trace HTTP redirect chain
.TP
hako\-certwatch(1)
batch TLS certificate expiry check
.TP
hako\-tlsping(1)
measure TCP + TLS handshake latency
