.TH MD5SUM 1 "2026-05-22" "hako" "hako utilities"
.SH NAME
md5sum \- compute MD5 message digests
.SH SYNOPSIS
.B md5sum
.RI [ file ...]
.SH DESCRIPTION
.B md5sum
computes the MD5 digest of each
.I file
and prints it to standard output in the format
.EX
\fIhash\fR  \fIfile\fR
.EE
.PP
If no
.I file
arguments are given, or if a filename of
.B \-
is specified, standard input is read.
.PP
If a file cannot be opened, an error is printed to standard error and processing
continues with the next file.
.SH EXAMPLES
.TP
.B md5sum file.txt
Compute the digest of
.BR file.txt .
.TP
.B "md5sum a.txt b.txt"
Compute digests for both files.
.TP
.B "echo hello | md5sum"
Digest standard input.
.SH EXIT STATUS
Always exits 0 (errors for individual files are reported to stderr but do not
affect the exit code).
.SH SEE ALSO
.BR md5sum (1),
.BR sha256sum (1),
.BR hako (1)
