.TH SLEEP 1 "2026-05-22" "hako" "hako utilities"
.SH NAME
sleep \- suspend execution for a number of seconds
.SH SYNOPSIS
.B sleep
.I seconds
.SH DESCRIPTION
.B sleep
pauses execution for the given number of
.IR seconds ,
which must be a non-negative integer.
Nothing is written to standard output.
.SH EXAMPLES
.TP
.B "sleep 5"
Pauses for five seconds.
.TP
.B "sleep 0"
Returns immediately.
.SH EXIT STATUS
.TP
.B 0
Success.
.TP
.B 1
Wrong number of arguments, or
.I seconds
is not a non-negative integer.
.SH SEE ALSO
.BR sleep (1),
.BR hako (1)
