.TH TIME 1 "2026-05-22" "hako" "hako utilities"
.SH NAME
time \- print the current UTC time
.SH SYNOPSIS
.B time
.SH DESCRIPTION
.B time
prints the current time in Coordinated Universal Time (UTC) to standard output,
in the format
.BR HH:MM:SS\ UTC .
.SH EXAMPLES
.EX
$ time
14:32:07 UTC
.EE
.SH EXIT STATUS
Always exits 0.
.SH SEE ALSO
.BR date (1),
.BR hako (1)
