.TH UNAME 1 "2026-05-22" "hako" "hako utilities"
.SH NAME
uname \- print system information
.SH SYNOPSIS
.B uname
.RB [ \-s ]
.RB [ \-n ]
.RB [ \-r ]
.RB [ \-v ]
.RB [ \-m ]
.RB [ \-a ]
.SH DESCRIPTION
.B uname
prints selected information about the operating system to standard output.
With no flags it prints the OS name (equivalent to
.BR \-s ).
Multiple flags may be combined; information is printed in the order
.IR "sysname nodename release version machine" .
.SH OPTIONS
.TP
.B \-s
System name (OS name), e.g.
.BR Linux .
.TP
.B \-n
Node name (hostname).
.TP
.B \-r
Kernel release, e.g.
.BR 6.1.0 .
.TP
.B \-v
Kernel version string, e.g.
.BR "#1 SMP" .
.TP
.B \-m
Machine hardware name, e.g.
.BR x86_64 .
.TP
.B \-a
Print all of the above in the order listed.
.SH EXAMPLES
.TP
.B uname
Print the OS name.
.TP
.B "uname -a"
Print all fields.
.TP
.B "uname -s -m"
Print OS name and machine type only.
.SH EXIT STATUS
.TP
.B 0
Success.
.TP
.B 1
System information could not be retrieved.
.SH SEE ALSO
.BR uname (1),
.BR hostname (1),
.BR hako (1)
