.TH WHOIS 1 "2026-05-22" "hako" "hako utilities"
.SH NAME
whois \- query WHOIS directory services
.SH SYNOPSIS
.B whois
.RI [ \-h\ server ]
.I query
.SH DESCRIPTION
.B whois
sends
.I query
to a WHOIS server and prints the response to standard output.
.PP
By default the query is sent to
.B whois.iana.org
and, if the response contains a
.B refer:
or
.B whois:
line, the query is automatically re-sent to that referred server and its
response is printed instead.
.PP
When an explicit server is given with
.BR \-h ,
referral is not followed.
.SH OPTIONS
.TP
.BI "\-h " server
Send the query to
.I server
instead of the default IANA server, and do not follow referrals.
.SH EXAMPLES
.TP
.B "whois example.com"
Look up the domain
.B example.com
via the IANA, following any referral.
.TP
.B "whois -h whois.verisign-grs.com example.com"
Query
.B whois.verisign-grs.com
directly without following referrals.
.SH EXIT STATUS
.TP
.B 0
Success.
.TP
.B 1
Wrong arguments, or a network error occurred.
.SH SEE ALSO
.BR whois (1),
.BR hako (1)
